### PR TITLE
Get data from Data Warehouse

### PR DESCRIPTION
**Pull request by dieguico**
I've found in Adobe Analyics API documentation a way to get reports from the Data Warehouse [(here)](https://marketing.adobe.com/developer/documentation/data-warehouse/r-report-2).

This pull request propose the inclusion of a new ~~function~~ method `QueueDataWarehouse`, and the slight adaptation of `GetElements` and `GetMetrics` to obtain the elements and metrics available on Data Warehouse.

The data from Data Warehouse can be retrieved with `GetReport` (it'd be interesting to modify the function to paginate the report if it's bigger than 20MB), or sent to a FTP server.

### CODE REVIEW

**Comment by randyzwitch** [comment]
Thanks for taking a shot at this @dieguico!

Can you make the method name `QueueDataWarehouse` instead of `QueueDataWareHouse`? Also, there are some reference errors in the TravisCI output that need to be fixed (looks like just documentation errors).

Even when you fix the documentation errors, the tests will still fail on Travis; it's a holiday weekend in the U.S., but I'll try and run the tests early next week to make sure everything still passes.

**Comment by dieguico** [comment]
I've just changed the name of the function and of the file. It's the first time I modify a package. How should I proceed to fix the documentation?

**Comment by randyzwitch** [comment]
Using RStudio, the documentation builds automatically using roxygen2. If you're not using RStudio, I can fix it, it's not a big deal.

**Comment by dieguico** [comment]
XD That's exactly how I build it. I thought I did it right XD Sorry!

**Comment by randyzwitch** [comment]
Validating now

**Comment by randyzwitch** [comment]
The good part is that none of the existing tests break. There are a few warnings still during build:

```R
==> devtools::check()

Updating RSiteCatalyst documentation
Loading RSiteCatalyst
Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building RSiteCatalyst ---------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build '/Users/randyzwitch/RSiteCatalyst'  \
  --no-resave-data --no-manual 

* checking for file ‘/Users/randyzwitch/RSiteCatalyst/DESCRIPTION’ ... OK
* preparing ‘RSiteCatalyst’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘RSiteCatalyst_1.4.9.tar.gz’

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking RSiteCatalyst ---------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD check  \
  '/var/folders/52/wl2rr05s3xgd8jy28j0_7bhm0000gn/T//RtmpsTz5Kj/RSiteCatalyst_1.4.9.tar.gz'  \
  --as-cran --timings --no-manual 

* using log directory ‘/Users/randyzwitch/RSiteCatalyst.Rcheck’
* using R version 3.3.0 (2016-05-03)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘RSiteCatalyst/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘RSiteCatalyst’ version ‘1.4.9’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘RSiteCatalyst’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
QueueDataWarehouse: no visible global function definition for
  ‘prettify’
QueueDataWarehouse: no visible binding for global variable
  ‘interval.seconds’
QueueDataWarehouse: no visible binding for global variable
  ‘max.attempts’
Undefined global functions or variables:
  interval.seconds max.attempts prettify
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... WARNING
Missing link or links in documentation object 'QueueDataWarehouse.Rd':
  ‘Report.Get’

See section 'Cross-references' in the 'Writing R Extensions' manual.

* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Documented arguments not in \usage in documentation object 'QueueDataWarehouse':
  ‘data.current’ ‘interval.seconds’ ‘max.attempts’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat-build.R’
  Running ‘testthat-get.R’ [2s/332s]
  Running ‘testthat-queuefallout.R’ [1s/89s]
  Running ‘testthat-queueovertime.R’ [1s/279s]
  Running ‘testthat-queuepathing.R’ [1s/86s]
  Running ‘testthat-queueranked.R’ [1s/299s]
  Running ‘testthat-queuesummary.R’ [1s/184s]
  Running ‘testthat-queuetrended.R’ [9s/459s]
  Running ‘testthat-save.R’ OK
* DONE
Status: 2 WARNINGs, 1 NOTE
 [1s/41s]

See
  ‘/Users/randyzwitch/RSiteCatalyst.Rcheck/00check.log’
for details.


checking Rd cross-references ... WARNING
Missing link or links in documentation object 'QueueDataWarehouse.Rd':
  ‘Report.Get’

See section 'Cross-references' in the 'Writing R Extensions' manual.


checking Rd \usage sections ... WARNING
Documented arguments not in \usage in documentation object 'QueueDataWarehouse':
  ‘data.current’ ‘interval.seconds’ ‘max.attempts’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.

checking R code for possible problems ... NOTE
QueueDataWarehouse: no visible global function definition for
  ‘prettify’
QueueDataWarehouse: no visible binding for global variable
  ‘interval.seconds’
QueueDataWarehouse: no visible binding for global variable
  ‘max.attempts’
Undefined global functions or variables:
  interval.seconds max.attempts prettify
R CMD check results
0 errors | 2 warnings | 1 note 

R CMD check succeeded
```

Also, could you add additional tests for your modifications of `GetElements` and `GetMetrics`? I'm not sure there is a good way to test `QueueDataWarehouse` since the report time can be so long,  but I'll think about that (since it's tied to my authenticated account)

**Comment by dieguico** [comment]
Randy, I've fixed several "minor" things, and I've created test for GetElements and GetMetrics (using the new "DataWarehouse" option). However, it did not pass the test since needs your credentials.

```
0.48schecking tests ... ERROR
Running the tests in ‘tests/testthat-build.R’ failed.
Last 13 lines of output:
  
  2. Error: Validate BuildRealTimeReportStructure using legacy credentials (@test-buildrealtimereportstructure.R#6) 
  Authentication failed due to errors
  1: SCAuth(Sys.getenv("USER", ""), Sys.getenv("SECRET", "")) at testthat/test-buildrealtimereportstructure.R:6
  2: stop("Authentication failed due to errors")
  
  testthat results ================================================================
  OK: 4 SKIPPED: 0 FAILED: 2
  1. Error: Validate BuildClassificationValueSegment using legacy credentials (@test-buildclassificationvaluesegment.R#6) 
  2. Error: Validate BuildRealTimeReportStructure using legacy credentials (@test-buildrealtimereportstructure.R#6) 
  
  Error: testthat unit tests failed
  Execution halted
```

There are easy requests that can be obtained from the DataWarehouse in minutes (usually). You can get them directly using the ReportGet function if they are smaller than 20MB (if they are bigger you'll need to modify the GetReport method to 'paginate' de report). However it'd be nice to test the FTP option as well. It worked to me but who knows :D

Please let me know if there's anything else I can do. :)

**Comment by randyzwitch** [comment]
Yes!

```R
* checking tests ...
  Running ‘testthat-build.R’
  Running ‘testthat-get.R’ [2s/363s]
  Running ‘testthat-queuefallout.R’ [1s/86s]
  Running ‘testthat-queueovertime.R’ [1s/292s]
  Running ‘testthat-queuepathing.R’ [1s/89s]
  Running ‘testthat-queueranked.R’ [1s/306s]
  Running ‘testthat-queuesummary.R’ [1s/198s]
  Running ‘testthat-queuetrended.R’ [8s/476s]
  Running ‘testthat-save.R’ OK
* DONE
Status: OK

 [1s/43s]


R CMD check results
0 errors | 0 warnings | 0 notes

R CMD check succeeded
```

Thanks for your hard work on this. I'm going to merge it into master to get Travis CI checks running. Then I'll submit to CRAN, probably early next week.

**Comment by dieguico** [comment]
:_) Thank you Randy! :D

My next move will be paginate `GetReport` and update the README ;)

**Pull request merged**
