### PR TITLE
Add ability to enQueue reports, and fetch data separately.

### PR DESCRIPTION
**Pull request by shashispace**
As per Randy's comment, I've attempted to split the SubmitJSONQueueReport into two parts, one for just enQueueing the job, and second for fetching it. This doesn't break existing API, but adds an option to just get the report id rather than wait for job to finish.
Also added two functions, GetReport gets the report data by report id, it's the second part of SubmitJSONQueueReport function.
Second one GetReportsByIds, this one fetches all the reports you've enqueued, you need to supply it with report ids list.

### CODE REVIEW

**Comment by randyzwitch** [comment]
Thanks! I'll try and review this over the weekend

**Comment by randyzwitch** [comment]
Looks like a handful of things going on here that need to be fixed:

```R
==> devtools::check()

Updating RSiteCatalyst documentation
Loading RSiteCatalyst
Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building RSiteCatalyst ---------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build '/Users/randyzwitch/RSiteCatalyst'  \
  --no-resave-data --no-manual 

* checking for file ‘/Users/randyzwitch/RSiteCatalyst/DESCRIPTION’ ... OK
* preparing ‘RSiteCatalyst’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘RSiteCatalyst_1.4.8.tar.gz’

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking RSiteCatalyst ---------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD check  \
  '/var/folders/52/wl2rr05s3xgd8jy28j0_7bhm0000gn/T//Rtmp54wjRs/RSiteCatalyst_1.4.8.tar.gz'  \
  --as-cran --timings --no-manual 

* using log directory ‘/Users/randyzwitch/RSiteCatalyst.Rcheck’
* using R version 3.2.4 (2016-03-10)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘RSiteCatalyst/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘RSiteCatalyst’ version ‘1.4.8’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘RSiteCatalyst’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
SubmitJsonQueueReport: no visible global function definition for
  ‘getReport’
* checking Rd files ... WARNING
prepare_Rd: GetReport.Rd:20-22: Dropping empty section \description
checkRd: (5) GetReport.Rd:0-36: Must have a \description
prepare_Rd: GetReportsByIds.Rd:20-22: Dropping empty section \description
checkRd: (5) GetReportsByIds.Rd:0-36: Must have a \description
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'GetReport'
  ‘print.attempts’

Undocumented arguments in documentation object 'GetReportsByIds'
  ‘print.attempts’

Undocumented arguments in documentation object 'SubmitJsonQueueReport'
  ‘enqueueOnly’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat-build.R’
  Running ‘testthat-get.R’ [2s/334s]
  Running ‘testthat-queuefallout.R’ ERROR
Running the tests in ‘tests/testthat-queuefallout.R’ failed.
Last 13 lines of output:
  Warning message:
  package 'testthat' was built under R version 3.2.5 
  > test_check("RSiteCatalyst", filter = "queuefallout")
  Loading required package: RSiteCatalyst
  Error in parse(text = lines, n = -1, srcfile = srcfile) : 
    testthat/test-queuefallout.R:59:1: unexpected '}'
  58: 
  59: }
      ^
  Calls: test_check ... FUN -> with_reporter -> force -> source_file -> parse
  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 0
  Execution halted
* DONE
Status: 1 ERROR, 2 WARNINGs, 1 NOTE


See
  ‘/Users/randyzwitch/RSiteCatalyst.Rcheck/00check.log’
for details.

checking tests ... ERROR
Running the tests in ‘tests/testthat-queuefallout.R’ failed.
Last 13 lines of output:
  Warning message:
  package 'testthat' was built under R version 3.2.5 
  > test_check("RSiteCatalyst", filter = "queuefallout")
  Loading required package: RSiteCatalyst
  Error in parse(text = lines, n = -1, srcfile = srcfile) : 
    testthat/test-queuefallout.R:59:1: unexpected '}'
  58: 
  59: }
      ^
  Calls: test_check ... FUN -> with_reporter -> force -> source_file -> parse
  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 0
  Execution halted

checking Rd files ... WARNING
prepare_Rd: GetReport.Rd:20-22: Dropping empty section \description
checkRd: (5) GetReport.Rd:0-36: Must have a \description
prepare_Rd: GetReportsByIds.Rd:20-22: Dropping empty section \description
checkRd: (5) GetReportsByIds.Rd:0-36: Must have a \description

checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'GetReport'
  ‘print.attempts’

Undocumented arguments in documentation object 'GetReportsByIds'
  ‘print.attempts’

Undocumented arguments in documentation object 'SubmitJsonQueueReport'
  ‘enqueueOnly’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.

checking R code for possible problems ... NOTE
SubmitJsonQueueReport: no visible global function definition for
  ‘getReport’
R CMD check results
1 error  | 2 warnings | 1 note 

R CMD check succeeded
```

**Comment by shashispace** [comment]
Thanks for your patience Randy - I've fixed things that I could see in the log, not sure if tests will pass though - perhaps the SCauth is private, so I am unable to test that part? Thanks.

**Comment by randyzwitch** [comment]
I forgot (until now) that Travis only runs tests from the account that set up the private keys (i.e. mine).

I'll try and merge this tonight to master, then fix any outstanding issues, since it isn't productive for me to just keep posting the logs for you without you having a way to run the test suite :)

**Comment by randyzwitch** [comment]
The CRAN checks pass, so I'm going to merge this into master. I'll fix the tests locally. Depending on whether I tackle any other outstanding issues, I'll send this to CRAN by end of the month (or sooner)

**Pull request merged**
