### PR TITLE
fixing OAUTH2 authentication

### PR DESCRIPTION
**Pull request by leocwlau**
1. Moved company='' within auth.method='OAUTH2', else company will always be '' when auth.method='OAUTH2'
2. Updated value extraction from sc.cred with new list 'credentials' for credential information

### CODE REVIEW

**Comment by randyzwitch** [comment]
Thanks, I'll try to test this out in the next day or two, this seems like a
pretty important fix to get pushed to CRAN.

**Comment by randyzwitch** [comment]
Thanks, this worked for me. In #223, you mentioned something about token refreshes and .httr-auth. Is that something you want to tackle as part of this PR or should I just merge this in?

**Comment by leocwlau** [comment]
Please just merge this in first. I wish to spend a bit more time on the other two issues to confirm their existence and try to fix in future PR(s)

**Comment by randyzwitch** [comment]
Sounds great. Thanks for this contribution, fixes from the community are always super appreciated!

**Pull request merged**
